orman:
  Paths:
    local_key_path: 
      Path: /Users/nevil/.orman/orman.key
      Description: Location to store your hashed password, used to encrypt your namespace (locally)
    local_namespace_path: 
      Path: /Users/nevil/.orman/namespace.orman
      Description: Loaction to store your encrpyted namespace file
  Endpoints:
    OrmanSpaces: 71v32103yg.execute-api.us-east-1.amazonaws.com/dev